import {
  SiAnthropic,
  SiClerk,
  SiCss3,
  SiDocker,
  SiFastapi,
  SiGithub,
  SiGooglegemini,
  SiGraphql,
  SiGreensock,
  SiHtml5,
  SiJavascript,
  SiLangchain,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOllama,
  SiOpenai,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiReactquery,
  SiRedux,
  SiSanity,
  SiSentry,
  SiShadcnui,
  SiStrapi,
  SiStripe,
  SiTailwindcss,
  SiTypescript,
  SiWordpress,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";
import { AiOutlineApi } from "react-icons/ai";
import { RiRobot2Line, RiZzzFill } from "react-icons/ri";
import { TbFileVector, TbSparkles } from "react-icons/tb";

const skillCategories = [
  {
    name: "AI Engineering",
    skills: [
      { name: "LangChain", icon: SiLangchain },
      { name: "Agentic RAG", icon: RiRobot2Line },
      { name: "OpenAI", icon: SiOpenai },
      { name: "Anthropic", icon: SiAnthropic },
      { name: "Gemini", icon: SiGooglegemini },
      { name: "Ollama", icon: SiOllama },
      { name: "Cursor", icon: TbSparkles },
    ],
  },
  {
    name: "Frontend",
    skills: [
      { name: "ReactJS", icon: SiReact },
      { name: "NextJS", icon: SiNextdotjs },
      { name: "TypeScript", icon: SiTypescript },
      { name: "JavaScript", icon: SiJavascript },
      { name: "TailwindCSS", icon: SiTailwindcss },
      { name: "Shadcn UI", icon: SiShadcnui },
      { name: "Redux", icon: SiRedux },
      { name: "Zustand", icon: RiZzzFill },
      { name: "Tanstack Query", icon: SiReactquery },
      { name: "HTML5", icon: SiHtml5 },
      { name: "CSS3", icon: SiCss3 },
      { name: "GSAP", icon: SiGreensock },
    ],
  },
  {
    name: "Backend",
    skills: [
      { name: "NodeJS", icon: SiNodedotjs },
      { name: "Python", icon: SiPython },
      { name: "FastAPI", icon: SiFastapi },
      { name: "PHP", icon: SiPhp },
      { name: "Laravel", icon: SiLaravel },
      { name: "Headless WP", icon: SiWordpress },
      { name: "StrapiJS", icon: SiStrapi },
      { name: "Stripe API", icon: SiStripe },
      { name: "REST API", icon: AiOutlineApi },
      { name: "GraphQL", icon: SiGraphql },
      { name: "Clerk", icon: SiClerk },
    ],
  },
  {
    name: "Database",
    skills: [
      { name: "MySQL", icon: SiMysql },
      { name: "PostgreSQL", icon: SiPostgresql },
      { name: "pgvector", icon: TbFileVector },
      { name: "MongoDB", icon: SiMongodb },
      { name: "Prisma", icon: SiPrisma },
    ],
  },
  {
    name: "DevOps & CMS",
    skills: [
      { name: "AWS", icon: FaAws },
      { name: "Docker", icon: SiDocker },
      { name: "Github", icon: SiGithub },
      { name: "Sanity.io", icon: SiSanity },
      { name: "WordPress", icon: SiWordpress },
      { name: "Sentry", icon: SiSentry },
    ],
  },
];

export default skillCategories;
